name: Mobile CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23.5.0
          cache: "npm"
          cache-dependency-path: "Mobile/package-lock.json"

      - name: Install Doppler CLI
        run: |
          # Install pre-reqs
          sudo apt-get update && sudo apt-get install -y apt-transport-https ca-certificates curl gnupg

          # Add Doppler's GPG key
          curl -sLf --retry 3 --tlsv1.2 --proto "=https" 'https://packages.doppler.com/public/cli/gpg.DE2A7741A397C129.key' | sudo apt-key add -

          # Add Doppler's apt repo
          echo "deb https://packages.doppler.com/public/cli/deb/debian any-version main" | sudo tee /etc/apt/sources.list.d/doppler-cli.list

          # Fetch and install latest doppler cli
          sudo apt-get update && sudo apt-get install -y doppler

      - name: Verify Doppler CLI installation
        run: doppler --version

      - name: Install dependencies
        working-directory: ./Mobile
        run: npm install

      - name: Run tests
        working-directory: ./Mobile
        run: |
          export HISTIGNORE='doppler run*'
          doppler run --token=${{ secrets.DOPPLER_TOKEN }} -- npx jest --coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Run linting
        working-directory: ./Mobile
        run: |
          export HISTIGNORE='doppler run*'
          doppler run --token=${{ secrets.DOPPLER_TOKEN }} -- npm run lint
